"""added unit col in usage record

Revision ID: 1a0cb0a2b13f
Revises: 7065761ce86e
Create Date: 2026-08-11 19:11:38.262069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0cb0a2b13f'
down_revision: Union[str, Sequence[str], None] = '7065761ce86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('unit', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_records', 'unit')
    # ### end Alembic commands ###
