"""track accurate per-chunk page ranges

Revision ID: 47f4cc2eeedf
Revises: 846980fa49e4
Create Date: 2026-08-06 12:34:16.988635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f4cc2eeedf'
down_revision: Union[str, Sequence[str], None] = '846980fa49e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('document_chunks', sa.Column('start_page', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('end_page', sa.Integer(), nullable=True))

    op.execute("UPDATE document_chunks SET start_page = page_number, end_page = page_number")

    op.alter_column('document_chunks', 'start_page', nullable=False)
    op.alter_column('document_chunks', 'end_page', nullable=False)
    op.drop_column('document_chunks', 'page_number')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('document_chunks', 'end_page')
    op.drop_column('document_chunks', 'start_page')
    # ### end Alembic commands ###
