"""add document scope to conversations

Revision ID: 5ee7a7cbfc15
Revises: 51b21746c680
Create Date: 2026-08-08 14:01:18.485986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee7a7cbfc15'
down_revision: Union[str, Sequence[str], None] = '51b21746c680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('document_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'document_id')
    op.drop_column('conversations', 'document_type')
    # ### end Alembic commands ###
