"""support multiple expected chunks per eval question

Revision ID: 7065761ce86e
Revises: ada68a5817fd
Create Date: 2026-08-10 16:40:04.000899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7065761ce86e'
down_revision: Union[str, Sequence[str], None] = 'ada68a5817fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_expected_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eval_question_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['eval_question_id'], ['eval_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('eval_questions_expected_chunk_id_fkey'), 'eval_questions', type_='foreignkey')
    op.drop_column('eval_questions', 'expected_chunk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eval_questions', sa.Column('expected_chunk_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('eval_questions_expected_chunk_id_fkey'), 'eval_questions', 'document_chunks', ['expected_chunk_id'], ['id'])
    op.drop_table('eval_expected_chunks')
    # ### end Alembic commands ###
