"""add owner, file_path, document_type to documents

Revision ID: 7c1dcd83d33f
Revises: b010570f97c9
Create Date: 2026-08-04 16:56:13.015253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1dcd83d33f'
down_revision: Union[str, Sequence[str], None] = 'b010570f97c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=False))
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'owner_id')
    # ### end Alembic commands ###
