"""support multi-page table continuation

Revision ID: 846980fa49e4
Revises: 79fd586195e0
Create Date: 2026-08-06 11:06:06.666585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846980fa49e4'
down_revision: Union[str, Sequence[str], None] = '79fd586195e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_tables', sa.Column('start_page', sa.Integer(), nullable=False))
    op.add_column('document_tables', sa.Column('end_page', sa.Integer(), nullable=False))
    op.drop_column('document_tables', 'page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_tables', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('document_tables', 'end_page')
    op.drop_column('document_tables', 'start_page')
    # ### end Alembic commands ###
