"""rename tokens_used to units_consumed  on usage_records

Revision ID: 8dcb1a3fb67f
Revises: 1a0cb0a2b13f
Create Date: 2026-08-12 12:54:49.992396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcb1a3fb67f'
down_revision: Union[str, Sequence[str], None] = '1a0cb0a2b13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('units_consumed', sa.Integer(), nullable=False))
    op.drop_column('usage_records', 'tokens_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('usage_records', 'units_consumed')
    # ### end Alembic commands ###
