"""add full-text search column to document_chunks

Revision ID: b79e1c43ae63
Revises: e36aaa7fc78c
Create Date: 2026-08-06 16:07:29.524292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b79e1c43ae63'
down_revision: Union[str, Sequence[str], None] = 'e36aaa7fc78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True))
    op.create_index('ix_chunks_content_tsv', 'document_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_content_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'content_tsv')
    # ### end Alembic commands ###
