"""add tier to users and file_size_bytes to documents

Revision ID: c242b8988303
Revises: 8dcb1a3fb67f
Create Date: 2026-08-17 10:18:23.554289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c242b8988303'
down_revision: Union[str, Sequence[str], None] = '8dcb1a3fb67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.String(), nullable=True, server_default='free'))
    op.add_column('documents', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
