"""constrain document_type values, add owner+type index

Revision ID: e36aaa7fc78c
Revises: cfdc96354859
Create Date: 2026-08-06 15:46:40.911160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36aaa7fc78c'
down_revision: Union[str, Sequence[str], None] = 'cfdc96354859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_owner_type', 'documents', ['owner_id', 'document_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_owner_type', table_name='documents')
    # ### end Alembic commands ###
