"""add data-only page range to table chunks

Revision ID: fc3de19bee04
Revises: 47f4cc2eeedf
Create Date: 2026-08-06 14:06:25.215838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3de19bee04'
down_revision: Union[str, Sequence[str], None] = '47f4cc2eeedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('data_start_page', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('data_end_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'data_end_page')
    op.drop_column('document_chunks', 'data_start_page')
    # ### end Alembic commands ###
